export enum ComplaintCategory {
  ELECTRICITY = 'ELECTRICITY',
  WATER = 'WATER',
  SEWAGE = 'SEWAGE',
  ROADS = 'ROADS',
  SANITATION = 'SANITATION',
  ENVIRONMENT = 'ENVIRONMENT',
  PUBLIC_CLEANLINESS = 'PUBLIC_CLEANLINESS',
  OTHER = 'OTHER',
}
