export enum NotificationType {
  COMPLAINT_SUBMITTED = 'COMPLAINT_SUBMITTED',
  COMPLAINT_STATUS_CHANGED = 'COMPLAINT_STATUS_CHANGED',
  COMPLAINT_ASSIGNED = 'COMPLAINT_ASSIGNED',
  COMPLAINT_RESOLVED = 'COMPLAINT_RESOLVED',
  COMPLAINT_CLOSED = 'COMPLAINT_CLOSED',
  COMPLAINT_COMMENT = 'COMPLAINT_COMMENT',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
