export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  MUNICIPAL_ADMIN = 'MUNICIPAL_ADMIN',
  DEPARTMENT_MANAGER = 'DEPARTMENT_MANAGER',
  DEPARTMENT_STAFF = 'DEPARTMENT_STAFF',
  CITIZEN = 'CITIZEN',
}
